name: Build and deploy

on:
  # Trigger the workflow on develop push (merged PR)
  push:
    branches:
      - develop

jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    environment: staging
    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          flutter-version: '2.0.5'

      - name: Get flutter dependencies.
        run: flutter pub get

      - name: Run widget tests, unit test for our flutter project.
        run: flutter test --machine --coverage

      - name: Setup lcov and modify the reports
        run: sudo apt-get install lcov && lcov --remove coverage/lcov.info 'lib/*/*.freezed.dart' 'lib/*/*.g.dart' 'lib/generated/*.dart' 'lib/flavors.dart' 'lib/exception/network_exceptions.dart' -o coverage/lcov.info

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: Upload coverage to codecov
          fail_ci_if_error: false
          verbose: true

  # TODO: deploy
