name: Lint and Test

on:
  # Trigger the workflow on push or pull request,
  # but push action is only for the feature branch
  pull_request:
    types: [ opened, synchronize, edited, reopened ]
  push:
    branches-ignore:
      - develop
      - 'release/**'
jobs:
  lint_and_test:
    name: Static code analyze & Unit test
    runs-on: ubuntu-latest
    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter

      - name: Get flutter dependencies.
        run: flutter pub get

      # Check for any formatting issues in the code.
      - run: flutter format --set-exit-if-changed .

      - name: Statically analyze the Dart code for any errors.
        run: flutter analyze .

      - name: Run widget tests, unit test for our flutter project.
        run: flutter test
